# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
      name: MyHostedVM

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Microsoft Azure Enterprise (83cc3e46-0000-4be1-a33f-f757490dcebc)'
    azureContainerRegistry: '{"loginServer":"infykubedemo.azurecr.io", "id" : "/subscriptions/83cc3e46-0000-4be1-a33f-f757490dcebc/resourceGroups/InfyKubeDemo/providers/Microsoft.ContainerRegistry/registries/infykubedemo"}'
    dockerComposeFile: 'docker-compose.yaml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'

- script: |
    echo Sample script
    echo See https://aka.ms/yaml
    
- task: HelmDeploy@0
  continueOnError: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'KubeMigrateServiceConnection'
    namespace: 'default'
    command: 'install'
    chartType: 'Name'
    chartName: 'bitnami/mongodb'
    releaseName: 'mongodb'
    arguments: '--set mongodbRootPassword=$(DB_ROOT_PASS) --set mongodbUsername=$(DB_USER) --set mongodbPassword=$(DB_PASS) --set mongodbDatabase=$(DB_NAME) --set externalAccess.enabled=false --set replicaSet.enabled=true --set auth.username=$(DB_USER) --set auth.password=$(DB_PASS) --set auth.database=$(DB_NAME)'

- task: HelmDeploy@0
  inputs:
    azureSubscriptionForACR: 'Microsoft Azure Enterprise (83cc3e46-0000-4be1-a33f-f757490dcebc)'
    azureResourceGroupForACR: 'InfyKubeDemo'
    azureContainerRegistry: 'infykubedemo.azurecr.io'
    command: 'save'
    chartNameForACR: 'sample-app-go'
    chartPathForACR: 'helm-charts'

- task: HelmDeploy@0
  continueOnError: true
  inputs:
     connectionType: 'Kubernetes Service Connection'
     kubernetesServiceConnection: 'KubeMigrateServiceConnection'
     namespace: 'default'
     command: 'install'
     chartType: 'Name'
     chartPath: 'infykubedemo.azurecr.io/helmcharts/sample-app-go'
     releaseName: 'sample-app-go'
     valueFile: 'helm-charts/to-do-api/values.yaml'
     arguments: '--set DB_CONNECTION=$(DB_CONNECTION) --set DB_NAME=$(DB_NAME) --set image.repository=$(IMAGE_REPOSITORY_API) --set ingress.hosts[0].host=$(KUBE_MIGRATE_HOSTNAME)'


